# Generated by Django 3.2.4 on 2021-06-27 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venue', '0001_initial'),
        ('performer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1000)),
                ('capacity', models.IntegerField()),
                ('date', models.DateTimeField(blank=True)),
                ('created_by', models.CharField(max_length=100)),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='performer.performer')),
                ('venue', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='venue.venue')),
            ],
        ),
    ]
