# Generated by Django 3.2.4 on 2021-06-27 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='venue_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
